### PR TITLE
Timetracking

### PR DESCRIPTION
**Pull request by Jonas-July**
Generally enables students to enter and correct the hours spent on their project, allows TLs to create intervals and to correct the records once students aren't allowed to after 3 weeks, and lets the Orga team specify categories and see an overview of each project.

Students:
- [x] Can enter hours spent on their project
- [x] Can specify the kind of work that was done in that time (Categories)
- [x] Can specify when that work was done (Intervals)
- [x] Can see hours entered broken down by member, interval and category
- [x] Can't change interval once archived (3 weeks after end date)
- [x] Can't see intervals that haven't started yet
- [x] Can add hours immediately in the table

TLs:
- [x] Can create intervals with start and end date
- [x] Can give intervals a readable name
- [x] Can edit and delete intervals
- [x] Can automatically generate intervals
- [x] Can see hours entered by students broken down by member, interval and category
- [x] Can correct hours entered by students once intervals are archived after 3 weeks

Orga:
- [x] Can specify categories which define certain kinds of work that time can be spent on
- [x] Can see total hours spent broken down by team
- [x] Can see hours spent broken down by member and interval
- [x] Direct link from project overview to timetracking page

### CODE REVIEW

**Comment by Jonas-July** [comment]
Related to #12

**Comment by Jonas-July** [comment]
This PR also contains the commits for Orgalogs; Either close #26 first or merge this and close #26 afterwards

**Comment by Jonas-July** [comment]
I'm leaving this PR for now until review.

All commits of the Orgalogs have been removed and the timetracking files are in separate folders.

**Comment by Jonas-July** [comment]
Rebased against current main with some commit improvements

**Review by bhaettasch — APPROVED** [review]

**Pull request merged**
